# Generated by Django 5.0.1 on 2026-02-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliated_hospital',
            field=models.ForeignKey(blank=True, help_text='For doctors: the hospital they belong to', limit_choices_to={'role': 'hospital'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital_code',
            field=models.CharField(blank=True, help_text='Unique tenant code for hospital accounts', max_length=20),
        ),
    ]
