/**
 * FhirExplorer.jsx
 * Interactive FHIR R4 resource JSON explorer with syntax-highlighted viewer,
 * resource type picker, and structure navigator.
 */
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
    FileText, Copy, Download, ChevronRight, Code, Database,
    CheckCircle2, ArrowRight, Search, Layers, Globe, Shield,
} from 'lucide-react';

const FHIR_RESOURCES = {
    'Condition (Anxiety)': {
        resourceType: 'Condition',
        id: 'medicode-cond-6a70',
        meta: { profile: ['http://hl7.org/fhir/StructureDefinition/Condition'], lastUpdated: '2026-02-20T14:32:00Z' },
        clinicalStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-clinical', code: 'active', display: 'Active' }] },
        verificationStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-ver-status', code: 'confirmed', display: 'Confirmed' }] },
        category: [{ coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-category', code: 'encounter-diagnosis', display: 'Encounter Diagnosis' }] }],
        severity: { coding: [{ system: 'http://snomed.info/sct', code: '24484000', display: 'Moderate' }] },
        code: { coding: [{ system: 'http://id.who.int/icd/release/11/mms', code: '6A70', display: 'Generalised Anxiety Disorder' }, { system: 'http://hl7.org/fhir/sid/icd-10', code: 'F41.1', display: 'Generalized anxiety disorder' }], text: 'Generalised Anxiety Disorder' },
        subject: { reference: 'Patient/P-2847', display: 'Rajesh Kumar' },
        encounter: { reference: 'Encounter/enc-20260220' },
        onsetDateTime: '2025-11-01',
        recordedDate: '2026-02-20T14:32:00Z',
        note: [{ text: 'Auto-generated by MediCode AI v2.0 — requires clinical validation' }],
    },
    'Condition (Depression)': {
        resourceType: 'Condition',
        id: 'medicode-cond-6a71',
        meta: { profile: ['http://hl7.org/fhir/StructureDefinition/Condition'], lastUpdated: '2026-02-19T11:15:00Z' },
        clinicalStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-clinical', code: 'active', display: 'Active' }] },
        verificationStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-ver-status', code: 'confirmed', display: 'Confirmed' }] },
        severity: { coding: [{ system: 'http://snomed.info/sct', code: '24112005', display: 'Severe' }] },
        code: { coding: [{ system: 'http://id.who.int/icd/release/11/mms', code: '6A70.1', display: 'Single Episode Depressive Disorder, Moderate' }], text: 'Major Depressive Disorder' },
        subject: { reference: 'Patient/P-2845', display: 'Priya Sharma' },
        onsetDateTime: '2025-08-15',
        recordedDate: '2026-02-19T11:15:00Z',
    },
    'Patient Resource': {
        resourceType: 'Patient',
        id: 'P-2847',
        meta: { profile: ['http://hl7.org/fhir/StructureDefinition/Patient'] },
        identifier: [{ system: 'http://abdm.gov.in/patients', value: 'ABDM-2847-2026' }],
        name: [{ use: 'official', family: 'Kumar', given: ['Rajesh'] }],
        gender: 'male',
        birthDate: '1968-03-15',
        telecom: [{ system: 'phone', value: '+919876543210', use: 'mobile' }],
        address: [{ city: 'New Delhi', state: 'Delhi', country: 'IN', postalCode: '110001' }],
    },
    'DiagnosticReport': {
        resourceType: 'DiagnosticReport',
        id: 'medicode-report-2026-1',
        status: 'final',
        category: [{ coding: [{ system: 'http://terminology.hl7.org/CodeSystem/v2-0074', code: 'OTH', display: 'Other' }] }],
        code: { coding: [{ system: 'http://loinc.org', code: '11488-4', display: 'Consultation note' }], text: 'AI-Generated Clinical Coding Report' },
        subject: { reference: 'Patient/P-2847', display: 'Rajesh Kumar' },
        effectiveDateTime: '2026-02-20T14:32:00Z',
        issued: '2026-02-20T14:32:03Z',
        performer: [{ display: 'MediCode AI v2.0' }],
        conclusion: 'Generalised Anxiety Disorder with concurrent insomnia. ICD-11 code 6A70 assigned with 92% confidence.',
    },
};

function JsonViewer({ data, depth = 0 }) {
    if (data === null) return <span style={{ color: '#f87171' }}>null</span>;
    if (typeof data === 'boolean') return <span style={{ color: '#fb923c' }}>{data.toString()}</span>;
    if (typeof data === 'number') return <span style={{ color: '#a78bfa' }}>{data}</span>;
    if (typeof data === 'string') return <span style={{ color: '#10b981' }}>"{data}"</span>;

    if (Array.isArray(data)) {
        if (data.length === 0) return <span style={{ color: 'rgba(148,163,184,0.5)' }}>[]</span>;
        return (
            <span>
                <span style={{ color: 'rgba(148,163,184,0.5)' }}>[</span>
                <div style={{ paddingLeft: 18 }}>
                    {data.map((item, i) => (
                        <div key={i}>
                            <JsonViewer data={item} depth={depth + 1} />
                            {i < data.length - 1 && <span style={{ color: 'rgba(148,163,184,0.4)' }}>,</span>}
                        </div>
                    ))}
                </div>
                <span style={{ color: 'rgba(148,163,184,0.5)' }}>]</span>
            </span>
        );
    }

    if (typeof data === 'object') {
        const keys = Object.keys(data);
        return (
            <span>
                <span style={{ color: 'rgba(148,163,184,0.5)' }}>{'{'}</span>
                <div style={{ paddingLeft: 18 }}>
                    {keys.map((key, i) => (
                        <div key={key}>
                            <span style={{ color: '#00d4ff' }}>"{key}"</span>
                            <span style={{ color: 'rgba(148,163,184,0.4)' }}>: </span>
                            <JsonViewer data={data[key]} depth={depth + 1} />
                            {i < keys.length - 1 && <span style={{ color: 'rgba(148,163,184,0.4)' }}>,</span>}
                        </div>
                    ))}
                </div>
                <span style={{ color: 'rgba(148,163,184,0.5)' }}>{'}'}</span>
            </span>
        );
    }

    return null;
}

export default function FhirExplorer() {
    const [selected, setSelected] = useState(Object.keys(FHIR_RESOURCES)[0]);
    const [copied, setCopied] = useState(false);
    const resource = FHIR_RESOURCES[selected];

    const handleCopy = () => {
        navigator.clipboard.writeText(JSON.stringify(resource, null, 2));
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div style={{ padding: '24px 28px', maxWidth: 1400 }}>
            {/* Header */}
            <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: 24 }}>
                <h1 style={{ fontSize: 24, fontWeight: 800 }}><span className="gradient-text">FHIR R4 Resource Explorer</span></h1>
                <p style={{ fontSize: 13, color: 'rgba(148,163,184,0.6)' }}>Browse and inspect FHIR R4 resources generated by MediCode AI for ABDM interoperability.</p>
            </motion.div>

            {/* Info badges */}
            <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
                style={{ display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' }}>
                {[
                    { icon: Globe, label: 'FHIR R4 Spec', color: '#00d4ff' },
                    { icon: Shield, label: 'ABDM Compliant', color: '#10b981' },
                    { icon: Database, label: 'HL7 v2.5 Compatible', color: '#8b5cf6' },
                    { icon: Layers, label: 'SNOMED CT Mapped', color: '#f59e0b' },
                ].map(({ icon: Icon, label, color }) => (
                    <span key={label} className="pill-badge" style={{ background: `${color}10`, border: `1px solid ${color}30`, color }}>
                        <Icon size={10} /> {label}
                    </span>
                ))}
            </motion.div>

            <div style={{ display: 'grid', gridTemplateColumns: '260px 1fr', gap: 16 }}>
                {/* Resource picker */}
                <motion.div initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }}
                    className="glass-panel-strong" style={{ borderRadius: 16, padding: 16, alignSelf: 'flex-start', position: 'sticky', top: 24 }}>
                    <p style={{ fontSize: 11, fontWeight: 600, color: 'rgba(148,163,184,0.5)', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                        Available Resources
                    </p>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                        {Object.keys(FHIR_RESOURCES).map(name => (
                            <motion.button key={name}
                                whileHover={{ scale: 1.02, x: 3 }}
                                whileTap={{ scale: 0.98 }}
                                onClick={() => setSelected(name)}
                                style={{
                                    padding: '10px 14px', borderRadius: 10, textAlign: 'left',
                                    background: selected === name ? 'rgba(0,212,255,0.1)' : 'transparent',
                                    border: selected === name ? '1px solid rgba(0,212,255,0.2)' : '1px solid transparent',
                                    color: selected === name ? '#00d4ff' : 'rgba(148,163,184,0.7)',
                                    fontSize: 12, fontWeight: selected === name ? 600 : 400,
                                    cursor: 'pointer', fontFamily: 'Inter',
                                    display: 'flex', alignItems: 'center', gap: 8,
                                    transition: 'all 0.2s ease',
                                }}>
                                <Code size={13} />
                                {name}
                                {selected === name && <ChevronRight size={12} style={{ marginLeft: 'auto' }} />}
                            </motion.button>
                        ))}
                    </div>
                </motion.div>

                {/* JSON viewer */}
                <motion.div initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }}
                    className="glass-panel-strong" style={{ borderRadius: 16, overflow: 'hidden' }}>
                    <div style={{
                        padding: '14px 20px',
                        borderBottom: '1px solid rgba(255,255,255,0.06)',
                        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                            <Code size={14} color="#00d4ff" />
                            <span style={{ fontSize: 13, fontWeight: 600, color: '#e2e8f0' }}>{selected}</span>
                            <span className="pill-badge pill-teal" style={{ fontSize: 9 }}>{resource.resourceType}</span>
                        </div>
                        <div style={{ display: 'flex', gap: 6 }}>
                            <motion.button whileHover={{ scale: 1.08 }} whileTap={{ scale: 0.92 }} onClick={handleCopy}
                                className="btn-neon-teal" style={{ padding: '5px 12px', borderRadius: 8, fontSize: 11, cursor: 'pointer', fontFamily: 'Inter', display: 'flex', alignItems: 'center', gap: 5 }}>
                                {copied ? <><CheckCircle2 size={11} /> Copied</> : <><Copy size={11} /> Copy</>}
                            </motion.button>
                            <motion.button whileHover={{ scale: 1.08 }} whileTap={{ scale: 0.92 }}
                                onClick={() => {
                                    const blob = new Blob([JSON.stringify(resource, null, 2)], { type: 'application/json' });
                                    const url = URL.createObjectURL(blob);
                                    const a = document.createElement('a'); a.href = url; a.download = `${selected.replace(/\s/g, '_')}.json`; a.click();
                                }}
                                className="btn-neon-teal" style={{ padding: '5px 12px', borderRadius: 8, fontSize: 11, cursor: 'pointer', fontFamily: 'Inter', display: 'flex', alignItems: 'center', gap: 5 }}>
                                <Download size={11} /> Download
                            </motion.button>
                        </div>
                    </div>
                    <div style={{
                        padding: '20px 24px',
                        fontFamily: '"Fira Code", "Cascadia Code", monospace',
                        fontSize: 12, lineHeight: 1.7,
                        maxHeight: 560, overflowY: 'auto',
                    }}>
                        <JsonViewer data={resource} />
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
